(ns org.apache.commons.collections4.set.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.apache.commons.collections4.set.AbstractNavigableSetDecorator])
(require '[org.apache.commons.collections4.set.AbstractSerializableSetDecorator])
(require '[org.apache.commons.collections4.set.AbstractSetDecorator])
(require '[org.apache.commons.collections4.set.AbstractSortedSetDecorator])
(require '[org.apache.commons.collections4.set.CompositeSet$SetMutator])
(require '[org.apache.commons.collections4.set.CompositeSet])
(require '[org.apache.commons.collections4.set.ListOrderedSet])
(require '[org.apache.commons.collections4.set.MapBackedSet])
(require '[org.apache.commons.collections4.set.PredicatedNavigableSet])
(require '[org.apache.commons.collections4.set.PredicatedSet])
(require '[org.apache.commons.collections4.set.PredicatedSortedSet])
(require '[org.apache.commons.collections4.set.TransformedNavigableSet])
(require '[org.apache.commons.collections4.set.TransformedSet])
(require '[org.apache.commons.collections4.set.TransformedSortedSet])
(require '[org.apache.commons.collections4.set.UnmodifiableNavigableSet])
(require '[org.apache.commons.collections4.set.UnmodifiableSet])
(require '[org.apache.commons.collections4.set.UnmodifiableSortedSet])
