(ns org.apache.commons.collections4.bidimap.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.apache.commons.collections4.bidimap.AbstractBidiMapDecorator])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$BidiMapIterator])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$EntrySet])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$EntrySetIterator])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$KeySet])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$KeySetIterator])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$MapEntry])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$Values])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$ValuesIterator])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap$View])
(require '[org.apache.commons.collections4.bidimap.AbstractDualBidiMap])
(require '[org.apache.commons.collections4.bidimap.AbstractOrderedBidiMapDecorator])
(require '[org.apache.commons.collections4.bidimap.AbstractSortedBidiMapDecorator])
(require '[org.apache.commons.collections4.bidimap.DualHashBidiMap])
(require '[org.apache.commons.collections4.bidimap.DualLinkedHashBidiMap])
(require '[org.apache.commons.collections4.bidimap.DualTreeBidiMap$BidiOrderedMapIterator])
(require '[org.apache.commons.collections4.bidimap.DualTreeBidiMap$ViewMap])
(require '[org.apache.commons.collections4.bidimap.DualTreeBidiMap])
(require '[org.apache.commons.collections4.bidimap.TreeBidiMap])
(require '[org.apache.commons.collections4.bidimap.UnmodifiableBidiMap])
(require '[org.apache.commons.collections4.bidimap.UnmodifiableOrderedBidiMap])
(require '[org.apache.commons.collections4.bidimap.UnmodifiableSortedBidiMap])
