(ns org.apache.commons.collections4.bag.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.apache.commons.collections4.bag.AbstractBagDecorator])
(require '[org.apache.commons.collections4.bag.AbstractMapBag$MutableInteger])
(require '[org.apache.commons.collections4.bag.AbstractMapBag])
(require '[org.apache.commons.collections4.bag.AbstractSortedBagDecorator])
(require '[org.apache.commons.collections4.bag.CollectionBag])
(require '[org.apache.commons.collections4.bag.CollectionSortedBag])
(require '[org.apache.commons.collections4.bag.HashBag])
(require '[org.apache.commons.collections4.bag.PredicatedBag])
(require '[org.apache.commons.collections4.bag.PredicatedSortedBag])
(require '[org.apache.commons.collections4.bag.SynchronizedBag])
(require '[org.apache.commons.collections4.bag.SynchronizedSortedBag])
(require '[org.apache.commons.collections4.bag.TransformedBag])
(require '[org.apache.commons.collections4.bag.TransformedSortedBag])
(require '[org.apache.commons.collections4.bag.TreeBag])
(require '[org.apache.commons.collections4.bag.UnmodifiableBag])
(require '[org.apache.commons.collections4.bag.UnmodifiableSortedBag])
