(ns core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[org.apache.commons.collections4.core])
(require '[org.apache.commons.collections4.bag.core])
(require '[org.apache.commons.collections4.bidimap.core])
(require '[org.apache.commons.collections4.collection.core])
(require '[org.apache.commons.collections4.comparators.core])
(require '[org.apache.commons.collections4.functors.core])
(require '[org.apache.commons.collections4.iterators.core])
(require '[org.apache.commons.collections4.keyvalue.core])
(require '[org.apache.commons.collections4.list.core])
(require '[org.apache.commons.collections4.map.core])
(require '[org.apache.commons.collections4.multimap.core])
(require '[org.apache.commons.collections4.multiset.core])
(require '[org.apache.commons.collections4.properties.core])
(require '[org.apache.commons.collections4.queue.core])
(require '[org.apache.commons.collections4.sequence.core])
(require '[org.apache.commons.collections4.set.core])
(require '[org.apache.commons.collections4.splitmap.core])
(require '[org.apache.commons.collections4.trie.core])
(require '[org.apache.commons.collections4.trie.analyzer.core])
